spring:
  profiles: prod1
eureka:
  datacenter: ali-hangzhou
  environment: prod1
  instance:
    secureVirtualHostName: ${spring.application.name}.1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  securePortEnabled: true
  nonSecurePortEnabled: true
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.16.251.155:${server.port}/eureka/
