#g关闭验证
management:
  security:
    enabled: false
security:
  user:
    name: user
    password: user
  basic:
    enabled: false
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          basedir: spring-cloud-config-repo/config-repo
          search-paths: spring-cloud-config-repo/config-repo
          uri: https://github.com/xie-summer/new-cloud/
          username: xieshengrong@live.com                                       # git仓库的账号
          password: password
---
spring:
  profiles: dev
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:8761/eureka
logging:
  config: classpath:logback-spring.xml
---
spring:
  profiles: prd
  rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-server:8761/eureka
logging:
  config: classpath:logback-spring.xml
---