#g关闭验证
management:
  security:
    enabled: false
security:
  user:
    name: user
    password: user
  basic:
    enabled: false
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          basedir: spring-cloud-config-repo/config-repo
          search-paths: spring-cloud-config-repo/config-repo
          uri: https://github.com/xie-summer/new-cloud/
          username: xieshengrong@live.com                                       # git仓库的账号
          password: password
