eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:user@localhost:8761/eureka/,http://localhost:8761/eureka/
    healthcheck:
      enabled: false